core/urls.py
from django.urls import path
from .views import *
from . import views
from .views import contactView, successView

app_name = 'core'
from core.sitemaps import  PostSitemap,StaticViewSitemap
from django.contrib.sitemaps.views import sitemap
from .views import *
sitemaps = {
    'post': PostSitemap,
    'static':StaticViewSitemap
}
urlpatterns = [
    path('',home, name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('searchposts/', views.searchposts, name='searchposts'),
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="sitemap"),
    path('register/', views.register, name='register'),
    #path('login/', LoginView.as_view(template_name ='user/login.html'), name='login'),
    path('login/', views.login_user, name='login'),


]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('SB', 'Shirts And Blouses'),
    ('TS', 'T-Shirts'),
    ('SK', 'Skirts'),
    ('HS', 'Hoodies&Sweatshirts')
)

LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    post_update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'BillingAddress', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a BillingAddress
    (Failed Checkout)
    3. Payment
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'BillingAddresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

from creditcards.models import CardNumberField, CardExpiryField, SecurityCodeField

class Information(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100,blank=True,null=True)
    city = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    cc_number = CardNumberField(('card number'))
    cc_expiry = CardExpiryField(('expiration date'))
    cc_code = SecurityCodeField(('security code'))
    def __str__(self):
        return "{} - {}".format(self.first_name, self.last_name)

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% load slide_template_tags %}
{% block head_title %}Mobile shop{% endblock %}
{% block content %}
<style>
	/*[ Block2 ]
///////////////////////////////////////////////////////////
*/
.block2-labelpromotion::before,
.block2-labelsale::before,
.block2-labelnew::before
{
  z-index: 100;
  font-family: Montserrat-Regular;
  font-size: 12px;
  color: white;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 22px;
  border-radius: 11px;
  position: absolute;
  top: 12px;
  left: 12px;
}

.block2-labelsale::before {
  background-color: white;
  color: #000;
  content: 'Sale';
}

.block2-labelnew::before {
  background-color: #007bff;
  content: 'New';
}

.block2-labelpromotion::before{
	background-color: #000;
	content: 'Promotion';
	width: 70px;
  }

  .btn-dark {
    color: #fff;
    background-color: #000;
    border-color: #000;
}

.btn-outline-dark {
    color: #000;
    border-color: #000;
}


</style>

	<!-- Slide1 -->
	<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">

				{% slides %}

				<!-- <div class="item-slick1 item2-slick1" style="background-image: url({% static 'images/master-slide-03.webp' %});">-->
<!--					<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">-->
<!--						<span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="rollIn">-->
<!--							Women Collection 2018-->
<!--						</span>-->
<!--						<h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="lightSpeedIn">-->
<!--							New arrivals-->
<!--						</h2>-->
<!--						<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="slideInUp">-->
<!--							&lt;!&ndash; Button &ndash;&gt;-->
<!--							<a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">-->
<!--								Shop Now-->
<!--							</a>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div> -->

			</div>
		</div>
	</section>

	<!-- Category start -->
	<style>
		.hov1{
			background-color: white !important;
			color: black !important;
			
		}
	</style>
	<section class="banner bgwhite p-t-40 p-b-40">
		<div class="container">
			<div class="row">

				{% categories_div %}

<!--				<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">-->
<!--					-->
<!--					<div class="block1 hov-img-zoom pos-relative m-b-30">-->
<!--						<img src="{% static 'images/banner-02.webp' %}" alt="IMG-BENNER">-->
<!--						<div class="block1-wrapbtn w-size2">-->
<!--							<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">-->
<!--								Dresses-->
<!--							</a>-->
<!--						</div>-->
<!--					</div>-->
<!--					-->
<!--					<div class="block1 hov-img-zoom pos-relative m-b-30">-->
<!--						<img src="{% static 'images/banner-05.webp' %}" alt="IMG-BENNER">-->
<!--						<div class="block1-wrapbtn w-size2">-->
<!--							<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">-->
<!--								Sunglasses-->
<!--							</a>-->
<!--						</div>-->
<!--					</div>-->
<!--					-->
<!--				</div>-->




			</div>
		</div>
	</section>

	<!-- New Product -->
	<style>
		.newproduct{
			margin-bottom: 2px;
			padding-bottom: 2px;
		}
	</style>
	<section class="newproduct bgwhite p-t-45 p-b-105">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Featured Products
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">

					{% for item in items %}
					
					<div class="item-slick2 p-l-15 p-r-15 mb-5">
						<!-- Block2 -->
						<div class="block2">
							
							<div class="block2-img wrap-pic-w of-hidden pos-relative block2-label{{item.get_label_display}}">
								<a href="{{item.get_absolute_url}}">
								<img src="{{ item.image.url }}" alt="IMG-PRODUCT" 
								style="height: 370px; width:100%; "></a>
							   

								<!-- <div class="block2-overlay trans-0-4">
									<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
										<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
										<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
									</a>
	
									
								</div> -->
							</div>
							

							<div class="block2-txt p-t-20">
								<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5" style="color: black;">
									{{ item.title }}
								</a>

								{% if item.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="color: black;">
									${{ item.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5">
									${{ item.discount_price }}
								</span>
								{% else %}
								<span class="block2-price m-text6 p-r-5" style="color: black;">
									${{ item.price }}
								</span>
								{% endif %}
								

								
							</div>
							
						</div>
					</div>
				
					{% endfor %}

					
				
				</div>
			</div>

		</div>
	</section>

	<!-- ------------------Banner2  start ------------------------>
	<style>
		.banner2{
			background-color: #fff;
			margin-right: 1rem;
			margin-left: 1rem;
			margin-bottom: 0 !important;
			padding-bottom: 0 !important;
		}

		.ban_img{
			height: 680px;
			width: 100%;
		}
		.ban5_img{
			height: 580px;
			width: 100%;
		}

		.btn-light {
			color: #000;
			background-color: #fff;
			border-color: #fff;
			border-radius: 20px;
		}
		.wrap-btn-slide1 a:hover{
			background-color: whitesmoke;
			color: #000 !important;
			opacity: 0.7;
	
		}
	</style>

	<!-- ------------------Banner2  start ------------------------>

	<!-- ------------------Banner4  start ------------------------>
<!-- Slide1 -->

<style>
	.slide1 button:hover{
		background-color: white !important;
		color: black;
	}
</style>

			
		
	
			






	

	{% endblock content %}


	

templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags%}

{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{message.tags}}">
    {{message}}
</div>
{% endfor %}
{% endif %}

<!-- Comment Form -->
<div class="border p-4 mb-5 mt-4 bg-light">
    <h3 class="card border-bottom mb-3 bg-secondary  text-light p-3">Login</h3>

    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}

        <input class="btn btn-outline-secondary my-2 my-sm-0" type="submit" value="login">
    </form>
    <div class="border-top mt-4 p-2"><small class="">you can <a href="{% url 'core:register' %}"> register</a></small></div>
</div>

{% endblock content %}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<div class="topbar-social">
					<a href="#" class="topbar-social-item fab fa-facebook"></a>
					<a href="#" class="topbar-social-item fab fa-instagram"></a>
					<a href="#" class="topbar-social-item fab fa-pinterest-p"></a>
					<a href="#" class="topbar-social-item fab fa-twitter"></a>
					<a href="#" class="topbar-social-item fab fa-youtube"></a>
				</div>



				<div class="topbar-child2">



					<div class="topbar-language rs1-select2">

					</div>
				</div>
			</div>

			<div class="wrap_header">
				<!-- Logo -->
				<a href="{% url 'core:home' %}" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">M</b>OBILE SHOP</p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li>

							{% categories %}

							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
							</li>
							<li>
								<a href="{% url 'account_logout' %}">Logout</a>
							</li>
							{% else %}
							<li>
								<a href="#">Login</a>
								<ul class="sub_menu">
									<li><a href="{% url 'core:login' %}">Login</a></li>
									<li><a href="{% url 'core:register' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->
				<div class="header-icons">


					<span class="linedivide1"></span>

					<div class="header-wrapicon2">

{% if user.is_authenticated %}
              <a href="{% url 'core:order-summary' %}" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">

</a>
                {% else %}
<a href="{% url 'core:login' %}" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
											<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>

</a>
                {% endif %}
						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">

							</ul>



							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'core:order-summary' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'core:checkout' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="{% url 'core:home' %}" class="logo-mobile">
					<p style="color: black; "><b style="font-size: 22px;">M</b>OBILE SHOP</p>
				</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">


					<span class="linedivide2"></span>

					<div class="header-wrapicon2">

						{% if user.is_authenticated %}
        <a href="{% url 'core:order-summary' %}"><img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
 											<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
                {% else %}
<a href="{% url 'core:login' %}"><img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
                {% endif %}


						</a>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">

							</ul>



							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'core:checkout' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">

					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">


							<div class="topbar-language rs1-select2">

							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="{% url 'core:home' %}">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'core:login' %}">Login</a></li>
							<li><a href="{% url 'core:register' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>
              {% else %}
                  ${{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ${{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}